In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px
from sklearn.metrics import confusion_matrix, classification_report
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import GridSearchCV

In [2]:
df=pd.read_csv('C:\\Users\\DELL\\jupi files\\Machine_Learning\\session_7\\Breast_Cancer.csv')
df.head(3)

id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0    842302         M        17.99         10.38           122.8     1001.0   
1    842517         M        20.57         17.77           132.9     1326.0   
2  84300903         M        19.69         21.25           130.0     1203.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   

   ...  texture_worst  perimeter_worst  area_worst  smoothness_worst  \
0  ...          17.33            184.6      2019.0            0.1622   
1  ...          23.41            158.8      1956.0            0.1238   
2  ...          25.53            152.5      1709.0            0.1444   

   compactness_worst  concavity_worst  concave points_worst  symmetry_worst  \
0             0.6656           0.7119                0.2654          0.4601   
1             0.1866           0.2416                0.1860          0.2750   
2             0.4245           0.4504                0.2430          0.3613   

   fractal_dimension_worst  Unnamed: 32  
0                  0.11890          NaN  
1                  0.08902          NaN  
2                  0.08758          NaN  

[3 rows x 33 columns]

In [3]:
df.columns

Index(['id', 'diagnosis', 'radius_mean', 'texture_mean', 'perimeter_mean',
       'area_mean', 'smoothness_mean', 'compactness_mean', 'concavity_mean',
       'concave points_mean', 'symmetry_mean', 'fractal_dimension_mean',
       'radius_se', 'texture_se', 'perimeter_se', 'area_se', 'smoothness_se',
       'compactness_se', 'concavity_se', 'concave points_se', 'symmetry_se',
       'fractal_dimension_se', 'radius_worst', 'texture_worst',
       'perimeter_worst', 'area_worst', 'smoothness_worst',
       'compactness_worst', 'concavity_worst', 'concave points_worst',
       'symmetry_worst', 'fractal_dimension_worst', 'Unnamed: 32'],
      dtype='object')

In [4]:
df=df.drop(columns=['id','Unnamed: 32'])
df.columns

Index(['diagnosis', 'radius_mean', 'texture_mean', 'perimeter_mean',
       'area_mean', 'smoothness_mean', 'compactness_mean', 'concavity_mean',
       'concave points_mean', 'symmetry_mean', 'fractal_dimension_mean',
       'radius_se', 'texture_se', 'perimeter_se', 'area_se', 'smoothness_se',
       'compactness_se', 'concavity_se', 'concave points_se', 'symmetry_se',
       'fractal_dimension_se', 'radius_worst', 'texture_worst',
       'perimeter_worst', 'area_worst', 'smoothness_worst',
       'compactness_worst', 'concavity_worst', 'concave points_worst',
       'symmetry_worst', 'fractal_dimension_worst'],
      dtype='object')

In [5]:
new_df=df['diagnosis']

In [6]:
le=LabelEncoder()

In [7]:
df['diagnosis']=le.fit_transform(new_df)
df['diagnosis'].value_counts()

diagnosis
0    357
1    212
Name: count, dtype: int64

In [8]:
le.classes_

array(['B', 'M'], dtype=object)

In [9]:
x=df.drop(columns='diagnosis')
y=df['diagnosis']

In [10]:
x_train, x_test, y_train, y_test= train_test_split(x,y, stratify=y, train_size=0.75, random_state=42)

In [11]:
knn=KNeighborsClassifier(n_neighbors=5)

# KNN

In [12]:
knn.fit(x_train,y_train)

KNeighborsClassifier()

In [13]:
y_pred=knn.predict(x_test)

In [14]:
com=confusion_matrix(y_test,y_pred)
com

array([[89,  1],
       [10, 43]], dtype=int64)

In [15]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.90      0.99      0.94        90
           1       0.98      0.81      0.89        53

    accuracy                           0.92       143
   macro avg       0.94      0.90      0.91       143
weighted avg       0.93      0.92      0.92       143



# Feature scalling with knn

In [16]:
sc=StandardScaler()

In [17]:
x_train_scale=sc.fit_transform(x_train)
x_test_scale=sc.fit_transform(x_test)

In [18]:
knn.fit(x_train_scale,y_train)

KNeighborsClassifier()

In [19]:
y_pred_scale=knn.predict(x_test_scale)

In [20]:
cm=confusion_matrix(y_test,y_pred_scale)
cm

array([[89,  1],
       [ 4, 49]], dtype=int64)

In [21]:
print(classification_report(y_test,y_pred_scale))

              precision    recall  f1-score   support

           0       0.96      0.99      0.97        90
           1       0.98      0.92      0.95        53

    accuracy                           0.97       143
   macro avg       0.97      0.96      0.96       143
weighted avg       0.97      0.97      0.96       143



In [22]:
knn=KNeighborsClassifier()
param={'n_neighbors': range(1,11)}


# GridSearch 

In [23]:
gs=GridSearchCV(estimator=knn, cv=5, param_grid=param, scoring='accuracy', n_jobs=-1, verbose=3)
gs.fit(x_train_scale, y_train)

Fitting 5 folds for each of 10 candidates, totalling 50 fits


GridSearchCV(cv=5, estimator=KNeighborsClassifier(), n_jobs=-1,
             param_grid={'n_neighbors': range(1, 11)}, scoring='accuracy',
             verbose=3)

In [24]:
gs.best_params_

{'n_neighbors': 3}

In [25]:
best_model=gs.best_estimator_

In [26]:
y_pred=best_model.predict(x_test_scale)

In [27]:
cm_2=confusion_matrix(y_test,y_pred)
cm_2

array([[88,  2],
       [ 4, 49]], dtype=int64)

In [28]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.96      0.98      0.97        90
           1       0.96      0.92      0.94        53

    accuracy                           0.96       143
   macro avg       0.96      0.95      0.95       143
weighted avg       0.96      0.96      0.96       143

