In [3]:
import numpy as np
import pandas as pd
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error, mean_squared_error
import plotly.express as px
import matplotlib.pyplot as plt

In [5]:
df=pd.DataFrame({'x':[1,2,3,4,5],'y':[10000,15000,20000,25000,30000]})
df

x      y
0  1  10000
1  2  15000
2  3  20000
3  4  25000
4  5  30000

In [6]:
plt.scatter(x=df['x'],y=df['y'])

In [7]:
x=df['x'].to_numpy().reshape(-1,1)
x

array([[1],
       [2],
       [3],
       [4],
       [5]], dtype=int64)

In [13]:
y=df['y']
y

0    10000
1    15000
2    20000
3    25000
4    30000
Name: y, dtype: int64

In [9]:
model=LinearRegression()

In [12]:
# isinstance(model, LinearRegression)

In [14]:
model.fit(x,y)

LinearRegression()

In [15]:
model.coef_

array([5000.])

In [16]:
model.intercept_

4999.999999999996

In [18]:
loe=int(input('enter your level of experince: '))
salary=model.coef_*loe + model.intercept_
salary

enter your level of experince:  5


array([30000.])

In [22]:
y_predict=model.predict(x)

In [23]:
mean_squared_error(y_predict,y)

3.308722450212111e-24

In [24]:
mean_absolute_error(y_predict,y)

1.0913936421275138e-12